USE lsystemsboxes;

ALTER TABLE EstadoCaja ADD FOREIGN KEY(idCaja) REFERENCES Caja(id) ON DELETE CASCADE;
ALTER TABLE EstadoCaja ADD FOREIGN KEY(idEstado) REFERENCES Estado(id) ON DELETE CASCADE;
ALTER TABLE Reciclaje ADD FOREIGN KEY(idCaja) REFERENCES Caja(id) ON DELETE CASCADE;
ALTER TABLE Reciclaje ADD FOREIGN KEY(idUsuario) REFERENCES Usuario(id) ON DELETE CASCADE;
ALTER TABLE Cuenta ADD FOREIGN KEY(idRol) REFERENCES Rol(id) ON DELETE CASCADE;
ALTER TABLE Cuenta ADD FOREIGN KEY(idUsuario) REFERENCES Usuario(id) ON DELETE CASCADE;
ALTER TABLE AvatarUsuario ADD FOREIGN KEY(idUsuario) REFERENCES Usuario(id) ON DELETE CASCADE;