ALTER TABLE EstadoCaja ADD FOREIGN KEY(id_Caja) REFERENCES Caja(id) ON DELETE CASCADE;
ALTER TABLE EstadoCaja ADD FOREIGN KEY(id_Estado) REFERENCES Estado(id) ON DELETE CASCADE;
ALTER TABLE Reciclaje ADD FOREIGN KEY(id_Caja) REFERENCES Caja(id) ON DELETE CASCADE;
ALTER TABLE Reciclaje ADD FOREIGN KEY(id_Usuario) REFERENCES Usuario(id) ON DELETE CASCADE;
ALTER TABLE Cuenta ADD FOREIGN KEY(id_Rol) REFERENCES Rol(id) ON DELETE CASCADE;
ALTER TABLE Cuenta ADD FOREIGN KEY(id_Usuario) REFERENCES Usuario(id) ON DELETE CASCADE;
ALTER TABLE AvatarUsuario ADD FOREIGN KEY(id_Usuario) REFERENCES Usuario(id) ON DELETE CASCADE;